// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/executionnode.proto

package executionnodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionNode_ExecuteTask_FullMethodName = "/executionnode.ExecutionNode/ExecuteTask"
)

// ExecutionNodeClient is the client API for ExecutionNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionNodeClient interface {
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type executionNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionNodeClient(cc grpc.ClientConnInterface) ExecutionNodeClient {
	return &executionNodeClient{cc}
}

func (c *executionNodeClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, ExecutionNode_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionNodeServer is the server API for ExecutionNode service.
// All implementations must embed UnimplementedExecutionNodeServer
// for forward compatibility.
type ExecutionNodeServer interface {
	ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedExecutionNodeServer()
}

// UnimplementedExecutionNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionNodeServer struct{}

func (UnimplementedExecutionNodeServer) ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedExecutionNodeServer) mustEmbedUnimplementedExecutionNodeServer() {}
func (UnimplementedExecutionNodeServer) testEmbeddedByValue()                       {}

// UnsafeExecutionNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionNodeServer will
// result in compilation errors.
type UnsafeExecutionNodeServer interface {
	mustEmbedUnimplementedExecutionNodeServer()
}

func RegisterExecutionNodeServer(s grpc.ServiceRegistrar, srv ExecutionNodeServer) {
	// If the following call pancis, it indicates UnimplementedExecutionNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionNode_ServiceDesc, srv)
}

func _ExecutionNode_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionNodeServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionNode_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionNodeServer).ExecuteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionNode_ServiceDesc is the grpc.ServiceDesc for ExecutionNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "executionnode.ExecutionNode",
	HandlerType: (*ExecutionNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _ExecutionNode_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/executionnode.proto",
}
